#!/bin/bash

RUN_DIR=/var/vcap/sys/run/redis
LOG_DIR=/var/vcap/sys/log/redis
STORE=/var/vcap/store/redis
PIDFILE=$RUN_DIR/redis.pid
RUN_AS_DAEMON=yes

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "redis"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $STORE

    # We do this because we want ENV variables used here, but Redis does not support it, so we explicitly state them.
    while read -r line; do eval echo $line; done < /var/vcap/jobs/redis/config/redis.conf | exec /var/vcap/packages/redis/bin/redis-server - >> $LOG_DIR/redis.stdout.log 2>>$LOG_DIR/redis.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;
  *)
  echo "Usage: redis_ctl {start|stop}" ;;
esac
exit 0
