source 'https://rubygems.org'

gemspec

group :test, :development do
  gem 'ci_reporter_rspec', '~> 1.0'
  gem 'method_profiler'
  gem 'rake', '~> 10.0'
  gem 'rspec', '~> 3.3.0'
  gem 'rubocop', '>= 0.24.1'
  gem 'simplecov'
  gem 'simplecov-rcov'
end
